### ISSUE TITLE
The directory name is invalid

### ISSUE THREAD

**Issue by SIREN587** [Lucas8x/luscious-downloader#6]
I have this weird problem, the folder is downloaded, the pics are inside but when i open them with irfan it says the directory is invalid. If i press one pic and right click open with say windows viewer it opens the pic. When i try to delete the folder it says its could not find the item. Paint also opens the pics

No idea how it happens or how to reproduce it other than it happened two times during dl of multiple galleries

**Comment by PiPerson7472** [comment]
I had this issue too. In about 40,000 albums I found that over 100 had an error. Now this is not a big deal because of how little it happens but the big issue is that the only thing that I have found to fix the issue is to reformat the drive then redownload whatever album messed up which means finding the album url again. With file explorer when trying to open the folder that the pictures are located in I get this error; C:\Folder\AlbumName is unavailable. If the location is on this PC, make sure the device or drive is connected or the disk is inserted, and then try again. If the location is on a network, make sure you are connected to the network or Internet, and then try again. If the location still can't be found, it may have been moved or deleted.

**Comment by SIREN587** [comment]
@Pieprson


No need to format, what i did is right click and you need winrar for this, 

right click -> add to archive -> delete folder after archiving and it zips and deletes the problematic folder. In my case i zipped the whole albums folder and made a new one

**Comment by Lucas8x** [comment]
Sorry about that, I realized that too and I'm trying to resolve
